version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/lib/docker/volumes/site/joomla:/var/www/html
    depends_on:
      - php
  php:
    build: php-fpm/.
    container_name: php
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - /var/lib/docker/volumes/site/joomla:/var/www/html
    depends_on:
      - mariadb
    links:
      - mariadb:mysql
    environment:
      JOOMLA_DB_HOST: mariadb:3306
      JOOMLA_DB_USER: cursodocker
      JOOMLA_DB_PASSWORD: cursodocker
      JOOMLA_DB_NAME: cursodocker
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8183:80"
    links:
      - mariadb:mysql
    environment:
      MYSQL_USERNAME: 'cursodocker'
      MYSQL_ROOT_PASSWORD: 'cursodocker'
      PMA_ARBITRARY: 1
      RM_HOST: mariadb:mysql
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    volumes:
      - /var/lib/docker/volumes/site/db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: cursodocker
      MYSQL_USER: cursodocker
      MYSQL_PASSWORD: cursodocker
      MYSQL_DATABASE: cursodocker
volumes:
  conf:
