version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./joomla:/var/www/html
    depends_on:
      - php
      - mysql
  php:
    image: php:7.1-fpm
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ./joomla:/var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: localhost:3306
      PMA_USER: root
      PMA_PASSWORD: ctic123
  mysql:
    image: mariadb:latest
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ctic123
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla123

volumes:
  conf:
  logs:
  joomla:
  db-dat:
